set(ARTOOLKIT_SOURCES
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/ar3DCreateHandle.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/ar3DUtil.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arCreateHandle.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arDetectMarker.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arDetectMarker2.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arFilterTransMat.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arGetLine.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arGetMarkerInfo.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arGetTransMat.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arGetTransMatStereo.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arImageProc.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arLabeling.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arLabelingSub/arLabelingPrivate.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arLabelingSub/arLabelingSub.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arLabelingSub/arLabelingSubDBIC.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arLabelingSub/arLabelingSubDBRC.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arLabelingSub/arLabelingSubDBZ.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arLabelingSub/arLabelingSubDWIC.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arLabelingSub/arLabelingSubDWRC.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arLabelingSub/arLabelingSubDWZ.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arLabelingSub/arLabelingSubEBIC.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arLabelingSub/arLabelingSubEBRC.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arLabelingSub/arLabelingSubEBZ.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arLabelingSub/arLabelingSubEWIC.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arLabelingSub/arLabelingSubEWRC.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arLabelingSub/arLabelingSubEWZ.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arPattAttach.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arPattCreateHandle.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arPattGetID.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arPattLoad.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arPattSave.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arUtil.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/mAlloc.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/mAllocDup.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/mAllocInv.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/mAllocMul.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/mAllocTrans.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/mAllocUnit.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/mDet.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/mDisp.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/mDup.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/mFree.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/mInv.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/mMul.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/mPCA.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/mSelfInv.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/mTrans.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/mUnit.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/paramChangeSize.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/paramClear.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/paramDecomp.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/paramDisp.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/paramDistortion.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/paramFile.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/paramGetPerspective.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/paramGL.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/paramLT.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/vAlloc.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/vDisp.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/vFree.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/vHouse.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/vInnerP.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/vTridiag.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR2/coord.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR2/featureMap.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR2/featureSet.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR2/handle.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR2/imageSet.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR2/jpeg.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR2/marker.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR2/matching.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR2/matching2.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR2/searchPoint.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR2/selectTemplate.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR2/surface.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR2/template.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR2/tracking.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR2/tracking2d.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR2/util.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/ARICP/icpCalibStereo.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/ARICP/icpCore.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/ARICP/icpHandle.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/ARICP/icpPoint.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/ARICP/icpPointRobust.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/ARICP/icpStereoHandle.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/ARICP/icpStereoPoint.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/ARICP/icpStereoPointRobust.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/ARICP/icpUtil.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/ARMulti/arMultiFreeConfig.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/ARMulti/arMultiGetTransMat.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/ARMulti/arMultiGetTransMatStereo.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/ARMulti/arMultiReadConfigFile.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/ARosg/arosg.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/ARUtil/crypt.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/ARUtil/crypt.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/ARUtil/file_utils.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/ARUtil/ftw.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/ARUtil/ioapi.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/ARUtil/ioapi.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/ARUtil/log.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/ARUtil/nftw.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/ARUtil/profile.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/ARUtil/system.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/ARUtil/thread_sub.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/ARUtil/time.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/ARUtil/unzip.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/ARUtil/unzip.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/ARUtil/zip.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/ARUtil/zip.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/ARWrapper/AndroidFeatures.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/ARWrapper/ARController.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/ARWrapper/ARMarker.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/ARWrapper/ARMarkerMulti.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/ARWrapper/ARMarkerNFT.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/ARWrapper/ARMarkerSquare.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/ARWrapper/ARPattern.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/ARWrapper/ARToolKitWrapperExportedAPI.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/ARWrapper/ARVideoSource.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/ARWrapper/ColorConversion.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/ARWrapper/trackingSub.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/ARWrapper/trackingSub.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Eden/ALFramework.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Eden/ALFramework.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Eden/CWaves.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Eden/CWaves.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Eden/EdenError.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Eden/EdenGLFont.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Eden/EdenMath.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Eden/EdenMessage.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Eden/EdenSound.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Eden/EdenSurfaces.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Eden/EdenTime.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Eden/EdenUtil.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Eden/glm.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Eden/gluttext/glutbitmap.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Eden/gluttext/glutstroke.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Eden/gluttext/glut_8x13.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Eden/gluttext/glut_9x15.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Eden/gluttext/glut_bitmap.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Eden/gluttext/glut_bwidth.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Eden/gluttext/glut_hel10.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Eden/gluttext/glut_hel12.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Eden/gluttext/glut_hel18.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Eden/gluttext/glut_mroman.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Eden/gluttext/glut_roman.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Eden/gluttext/glut_stroke.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Eden/gluttext/glut_swidth.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Eden/gluttext/glut_tr10.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Eden/gluttext/glut_tr24.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Eden/readtex.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Gl/argBase.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Gl/argDraw.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Gl/argDrawImage.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Gl/argDrawMode.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Gl/argFunction.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Gl/argPrivate.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Gl/argWindow.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Gl/gsub_mtx.c)
SET(ARTOOLKIT_GL_SOURCES_DESKTOP
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Gl/gsub_lite.c)
SET(ARTOOLKIT_GL_SOURCES_MOBILE
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Gl/glStateCache.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Gl/glStateCache2.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Gl/gsub_es.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Gl/gsub_es2.c)
SET(ARTOOLKIT_SOURCES_ANDROID
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/ARUtil/android_system_property_get.c)
SET(ARTOOLKIT_SOURCES_WINDOWS_RT
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/ARToolKitComponent/ARToolKitComponent.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/ARToolKitComponent/ARToolKitComponent.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/ARToolKitComponent/pch.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/ARToolKitComponent/pch.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/ARUtil/thread_sub_winrt.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/ARUtil/thread_sub_winrt.h
  # ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/ARgsubD3D/ARgsubD3D.Shared/ArD3dCube.cpp
  # ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/ARgsubD3D/ARgsubD3D.Shared/ArD3dCube.h
  # ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/ARgsubD3D/ARgsubD3D.Shared/ArD3dDeviceContext.cpp
  # ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/ARgsubD3D/ARgsubD3D.Shared/ArD3dDeviceContext.h
  # ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/ARgsubD3D/ARgsubD3D.Shared/ArD3dImage.cpp
  # ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/ARgsubD3D/ARgsubD3D.Shared/ArD3dImage.h
  # ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/ARgsubD3D/ARgsubD3D.Shared/ArD3dIObject.h
  # ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/ARgsubD3D/ARgsubD3D.Shared/ArD3dPanel.cpp
  # ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/ARgsubD3D/ARgsubD3D.Shared/ArD3dPanel.h
  # ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/ARgsubD3D/ARgsubD3D.Shared/Helper.h
  # ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/ARgsubD3D/ARgsubD3D.Shared/pch.cpp
  # ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/ARgsubD3D/ARgsubD3D.Shared/pch.h
  # ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/ARgsubD3D/ARgsubD3D.Shared/ShaderConstantsDefinitons.h
  # ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/ARgsubD3D/ARgsubD3D.Shared/SimplePixelShader.hlsl
  # ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/ARgsubD3D/ARgsubD3D.Shared/SimpleVertexShader.hlsl
  # ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/ARgsubD3D/ARgsubD3D.Shared/SolidColorPixelShader.hlsl
  )
SET(ARTOOLKIT_KPM_SOURCES
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/KPM/FreakMatcher/detectors/DoG_scale_invariant_detector.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/KPM/FreakMatcher/detectors/DoG_scale_invariant_detector.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/KPM/FreakMatcher/detectors/gaussian_scale_space_pyramid.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/KPM/FreakMatcher/detectors/gaussian_scale_space_pyramid.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/KPM/FreakMatcher/detectors/gradients.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/KPM/FreakMatcher/detectors/gradients.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/KPM/FreakMatcher/detectors/harris-inline.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/KPM/FreakMatcher/detectors/harris.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/KPM/FreakMatcher/detectors/harris.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/KPM/FreakMatcher/detectors/interpolate.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/KPM/FreakMatcher/detectors/orientation_assignment.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/KPM/FreakMatcher/detectors/orientation_assignment.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/KPM/FreakMatcher/detectors/pyramid-inline.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/KPM/FreakMatcher/detectors/pyramid.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/KPM/FreakMatcher/detectors/pyramid.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/KPM/FreakMatcher/facade/visual_database_facade.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/KPM/FreakMatcher/facade/visual_database_facade.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/KPM/FreakMatcher/framework/date_time.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/KPM/FreakMatcher/framework/date_time.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/KPM/FreakMatcher/framework/error.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/KPM/FreakMatcher/framework/exception.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/KPM/FreakMatcher/framework/image.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/KPM/FreakMatcher/framework/image.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/KPM/FreakMatcher/framework/image_utils.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/KPM/FreakMatcher/framework/logger.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/KPM/FreakMatcher/framework/logger.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/KPM/FreakMatcher/framework/timers.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/KPM/FreakMatcher/framework/timers.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/KPM/FreakMatcher/homography_estimation/homography_solver.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/KPM/FreakMatcher/homography_estimation/robust_homography.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/KPM/FreakMatcher/matchers/binary_hierarchical_clustering.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/KPM/FreakMatcher/matchers/feature_matcher-inline.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/KPM/FreakMatcher/matchers/feature_matcher.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/KPM/FreakMatcher/matchers/feature_point.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/KPM/FreakMatcher/matchers/feature_store.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/KPM/FreakMatcher/matchers/feature_store_io.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/KPM/FreakMatcher/matchers/feature_store_io.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/KPM/FreakMatcher/matchers/freak.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/KPM/FreakMatcher/matchers/freak.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/KPM/FreakMatcher/matchers/freak84-inline.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/KPM/FreakMatcher/matchers/hough_similarity_voting.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/KPM/FreakMatcher/matchers/hough_similarity_voting.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/KPM/FreakMatcher/matchers/keyframe.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/KPM/FreakMatcher/matchers/kmedoids.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/KPM/FreakMatcher/matchers/matcher_types.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/KPM/FreakMatcher/matchers/visual_database-inline.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/KPM/FreakMatcher/matchers/visual_database.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/KPM/FreakMatcher/matchers/visual_database_io.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/KPM/FreakMatcher/matchers/visual_database_io.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/KPM/FreakMatcher/matchers/visual_database_types.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/KPM/FreakMatcher/math/cholesky.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/KPM/FreakMatcher/math/cholesky_linear_solvers.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/KPM/FreakMatcher/math/geometry.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/KPM/FreakMatcher/math/hamming.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/KPM/FreakMatcher/math/homography.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/KPM/FreakMatcher/math/indexing.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/KPM/FreakMatcher/math/linear_algebra.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/KPM/FreakMatcher/math/linear_solvers.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/KPM/FreakMatcher/math/math_io.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/KPM/FreakMatcher/math/math_io.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/KPM/FreakMatcher/math/math_utils.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/KPM/FreakMatcher/math/matrix.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/KPM/FreakMatcher/math/polynomial.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/KPM/FreakMatcher/math/quaternion.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/KPM/FreakMatcher/math/rand.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/KPM/FreakMatcher/math/robustifiers.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/KPM/FreakMatcher/utils/feature_drawing.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/KPM/FreakMatcher/utils/partial_sort.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/KPM/FreakMatcher/utils/point.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/KPM/kpmFopen.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/KPM/kpmFopen.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/KPM/kpmHandle.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/KPM/kpmMatching.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/KPM/kpmPrivate.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/KPM/kpmRefDataSet.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/KPM/kpmResult.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/KPM/kpmUtil.cpp)
SET(ARTOOLKIT_VIDEO_SOURCES
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Video/video.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Video/video2.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Video/videoAspectRatio.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Video/videoSaveImage.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Video/Dummy/videoDummy.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Video/Dummy/videoDummy.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Video/Image/videoImage.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Video/Image/videoImage.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Video/cparamSearch.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Video/cparamSearch.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Video/nxjson.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Video/nxjson.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Video/videoLuma.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Video/videoRGBA.c
)
SET(ARTOOLKIT_VIDEO_SOURCES_ANDROID
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Video/Android/sqlite3.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Video/Android/sqlite3.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Video/Android/videoAndroid.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Video/Android/videoAndroid.h)
SET(ARTOOLKIT_VIDEO_SOURCES_APPLE
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Video/AVFoundation/CameraVideo.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Video/AVFoundation/CameraVideo.m
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Video/AVFoundation/cparams.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Video/AVFoundation/cparams.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Video/AVFoundation/MovieVideo.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Video/AVFoundation/MovieVideo.m
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Video/AVFoundation/videoAVFoundation.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Video/AVFoundation/videoAVFoundation.m
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Video/AVFoundation/videoAVFoundationCameraVideoTookPictureDelegate.h)
SET(ARTOOLKIT_VIDEO_SOURCES_LINUX
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Video/GStreamer/videoGStreamer.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Video/GStreamer/videoGStreamer.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Video/Video4Linux2/videoV4L2.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Video/Video4Linux2/videoV4L2.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Video/libdc1394/video1394.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Video/libdc1394/video1394.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Video/libdc1394/video1394Format.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Video/libdc1394/video1394Private.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Video/libdc1394/video1394Setting.c)
SET(ARTOOLKIT_VIDEO_SOURCES_WINDOWS_RT
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Video/WindowsMediaCapture/CaptureFrameGrabber/CaptureFrameGrabber.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Video/WindowsMediaCapture/CaptureFrameGrabber/CaptureFrameGrabber.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Video/WindowsMediaCapture/CaptureFrameGrabber/MediaSink.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Video/WindowsMediaCapture/CaptureFrameGrabber/MediaStreamSink.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Video/WindowsMediaCapture/CaptureFrameGrabber/MediaStreamSink.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Video/WindowsMediaCapture/CaptureFrameGrabber/MFIncludes.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Video/WindowsMediaCapture/videoWindowsMediaCapture.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Video/WindowsMediaCapture/videoWinMC.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Video/WindowsMediaCapture/WindowsMediaCapture.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Video/WindowsMediaCapture/WindowsMediaCapture.h
)
SET(ARTOOLKIT_VIDEO_SOURCES_WINDOWS
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Video/WindowsMediaFoundation/BufferLock.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Video/WindowsMediaFoundation/LogMediaType.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Video/WindowsMediaFoundation/videoWindowsMediaFoundation.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Video/WindowsMediaFoundation/videoWindowsMediaFoundation.h)
