set(ARTOOLKIT_SOURCES
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/ar3DCreateHandle.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/ar3DUtil.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arCreateHandle.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arDetectMarker.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arDetectMarker2.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arFilterTransMat.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arGetLine.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arGetMarkerInfo.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arGetTransMat.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arGetTransMatStereo.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arImageProc.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arLabeling.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arLabelingSub/arLabelingSubDBI3C.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arLabelingSub/arLabelingSubDBI3C565.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arLabelingSub/arLabelingSubDBI3CA.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arLabelingSub/arLabelingSubDBI3CA4444.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arLabelingSub/arLabelingSubDBI3CA5551.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arLabelingSub/arLabelingSubDBIA3C.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arLabelingSub/arLabelingSubDBIC.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arLabelingSub/arLabelingSubDBICY.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arLabelingSub/arLabelingSubDBIYC.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arLabelingSub/arLabelingSubDBR3C.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arLabelingSub/arLabelingSubDBR3C565.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arLabelingSub/arLabelingSubDBR3CA.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arLabelingSub/arLabelingSubDBR3CA4444.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arLabelingSub/arLabelingSubDBR3CA5551.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arLabelingSub/arLabelingSubDBRA3C.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arLabelingSub/arLabelingSubDBRC.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arLabelingSub/arLabelingSubDBRCY.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arLabelingSub/arLabelingSubDBRYC.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arLabelingSub/arLabelingSubDBZ.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arLabelingSub/arLabelingSubDWI3C.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arLabelingSub/arLabelingSubDWI3C565.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arLabelingSub/arLabelingSubDWI3CA.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arLabelingSub/arLabelingSubDWI3CA4444.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arLabelingSub/arLabelingSubDWI3CA5551.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arLabelingSub/arLabelingSubDWIA3C.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arLabelingSub/arLabelingSubDWIC.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arLabelingSub/arLabelingSubDWICY.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arLabelingSub/arLabelingSubDWIYC.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arLabelingSub/arLabelingSubDWR3C.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arLabelingSub/arLabelingSubDWR3C565.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arLabelingSub/arLabelingSubDWR3CA.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arLabelingSub/arLabelingSubDWR3CA4444.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arLabelingSub/arLabelingSubDWR3CA5551.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arLabelingSub/arLabelingSubDWRA3C.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arLabelingSub/arLabelingSubDWRC.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arLabelingSub/arLabelingSubDWRCY.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arLabelingSub/arLabelingSubDWRYC.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arLabelingSub/arLabelingSubDWZ.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arLabelingSub/arLabelingSubEBI3C.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arLabelingSub/arLabelingSubEBI3C565.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arLabelingSub/arLabelingSubEBI3CA.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arLabelingSub/arLabelingSubEBI3CA4444.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arLabelingSub/arLabelingSubEBI3CA5551.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arLabelingSub/arLabelingSubEBIA3C.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arLabelingSub/arLabelingSubEBIC.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arLabelingSub/arLabelingSubEBICY.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arLabelingSub/arLabelingSubEBIYC.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arLabelingSub/arLabelingSubEBR3C.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arLabelingSub/arLabelingSubEBR3C565.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arLabelingSub/arLabelingSubEBR3CA.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arLabelingSub/arLabelingSubEBR3CA4444.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arLabelingSub/arLabelingSubEBR3CA5551.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arLabelingSub/arLabelingSubEBRA3C.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arLabelingSub/arLabelingSubEBRC.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arLabelingSub/arLabelingSubEBRCY.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arLabelingSub/arLabelingSubEBRYC.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arLabelingSub/arLabelingSubEBZ.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arLabelingSub/arLabelingSubEWI3C.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arLabelingSub/arLabelingSubEWI3C565.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arLabelingSub/arLabelingSubEWI3CA.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arLabelingSub/arLabelingSubEWI3CA4444.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arLabelingSub/arLabelingSubEWI3CA5551.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arLabelingSub/arLabelingSubEWIA3C.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arLabelingSub/arLabelingSubEWIC.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arLabelingSub/arLabelingSubEWICY.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arLabelingSub/arLabelingSubEWIYC.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arLabelingSub/arLabelingSubEWR3C.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arLabelingSub/arLabelingSubEWR3C565.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arLabelingSub/arLabelingSubEWR3CA.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arLabelingSub/arLabelingSubEWR3CA4444.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arLabelingSub/arLabelingSubEWR3CA5551.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arLabelingSub/arLabelingSubEWRA3C.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arLabelingSub/arLabelingSubEWRC.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arLabelingSub/arLabelingSubEWRCY.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arLabelingSub/arLabelingSubEWRYC.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arLabelingSub/arLabelingSubEWZ.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arPattAttach.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arPattCreateHandle.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arPattGetID.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arPattLoad.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arPattSave.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/arUtil.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/mAlloc.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/mAllocDup.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/mAllocInv.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/mAllocMul.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/mAllocTrans.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/mAllocUnit.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/mDet.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/mDisp.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/mDup.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/mFree.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/mInv.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/mMul.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/mPCA.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/mSelfInv.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/mTrans.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/mUnit.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/paramChangeSize.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/paramClear.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/paramDecomp.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/paramDisp.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/paramDistortion.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/paramFile.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/paramGetPerspective.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/paramLT.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/vAlloc.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/vDisp.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/vFree.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/vHouse.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/vInnerP.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR/vTridiag.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR2/coord.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR2/featureMap.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR2/featureSet.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR2/handle.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR2/imageSet.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR2/jpeg.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR2/marker.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR2/matching.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR2/matching2.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR2/searchPoint.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR2/selectTemplate.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR2/surface.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR2/template.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR2/tracking.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR2/tracking2d.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/AR2/util.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/ARICP/icpCalibStereo.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/ARICP/icpCore.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/ARICP/icpHandle.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/ARICP/icpPoint.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/ARICP/icpPointRobust.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/ARICP/icpStereoHandle.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/ARICP/icpStereoPoint.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/ARICP/icpStereoPointRobust.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/ARICP/icpUtil.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/ARMulti/arMultiFreeConfig.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/ARMulti/arMultiGetTransMat.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/ARMulti/arMultiGetTransMatStereo.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/ARMulti/arMultiReadConfigFile.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/ARosg/arosg.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/ARWrapper/AndroidFeatures.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/ARWrapper/AndroidVideoSource.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/ARWrapper/ARController.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/ARWrapper/ARMarker.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/ARWrapper/ARMarkerMulti.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/ARWrapper/ARMarkerNFT.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/ARWrapper/ARMarkerSquare.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/ARWrapper/ARPattern.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/ARWrapper/ARToolKitVideoSource.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/ARWrapper/ARToolKitWrapperExportedAPI.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/ARWrapper/ColorConversion.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/ARWrapper/trackingSub.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/ARWrapper/VideoSource.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Eden/ALFramework.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Eden/CWaves.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Eden/EdenError.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Eden/EdenGLFont.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Eden/EdenMath.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Eden/EdenMessage.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Eden/EdenSound.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Eden/EdenSurfaces.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Eden/EdenTime.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Eden/EdenUtil.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Eden/glm.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Eden/gluttext/glut_8x13.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Eden/gluttext/glut_9x15.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Eden/gluttext/glut_bitmap.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Eden/gluttext/glut_bwidth.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Eden/gluttext/glut_hel10.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Eden/gluttext/glut_hel12.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Eden/gluttext/glut_hel18.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Eden/gluttext/glut_mroman.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Eden/gluttext/glut_roman.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Eden/gluttext/glut_stroke.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Eden/gluttext/glut_swidth.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Eden/gluttext/glut_tr10.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Eden/gluttext/glut_tr24.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Eden/readtex.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Util/profile.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Util/thread_sub.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Gl/gsub_mtx.c)
SET(ARTOOLKIT_GL_SOURCES_DESKTOP
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Gl/gsub_lite.c)
SET(ARTOOLKIT_GL_SOURCES_MOBILE
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Gl/glStateCache.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Gl/glStateCache2.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Gl/gsub_es2.c)
SET(ARTOOLKIT_SOURCES_WINDOWS
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/ARToolKitComponent/ARToolKitComponent.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/ARToolKitComponent/pch.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Util/thread_sub_winrt.cpp)
SET(ARTOOLKIT_KPM_SOURCES
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/KPM/FreakMatcher/detectors/DoG_scale_invariant_detector.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/KPM/FreakMatcher/detectors/gaussian_scale_space_pyramid.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/KPM/FreakMatcher/detectors/gradients.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/KPM/FreakMatcher/detectors/harris.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/KPM/FreakMatcher/detectors/orientation_assignment.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/KPM/FreakMatcher/detectors/pyramid.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/KPM/FreakMatcher/facade/visual_database_facade.cpp
  #${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/KPM/FreakMatcher/facade/visual_database_opencvfacade.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/KPM/FreakMatcher/framework/date_time.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/KPM/FreakMatcher/framework/image.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/KPM/FreakMatcher/framework/logger.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/KPM/FreakMatcher/framework/timers.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/KPM/FreakMatcher/matchers/feature_store_io.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/KPM/FreakMatcher/matchers/freak.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/KPM/FreakMatcher/matchers/hough_similarity_voting.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/KPM/FreakMatcher/matchers/visual_database_io.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/KPM/FreakMatcher/math/math_io.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/KPM/kpmFopen.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/KPM/kpmHandle.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/KPM/kpmMatching.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/KPM/kpmRefDataSet.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/KPM/kpmResult.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/KPM/kpmUtil.cpp)  
SET(ARTOOLKIT_VIDEO_SOURCES
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Video/video.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Video/video2.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Video/videoAspectRatio.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/Video/videoSaveImage.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/VideoDummy/videoDummy.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/VideoImage/videoImage.c)
SET(ARTOOLKIT_VIDEO_SOURCES_ANDROID  
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/VideoAndroid/cparamSearch.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/VideoAndroid/nxjson.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/VideoAndroid/sqlite3.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/VideoAndroid/videoAndroid.c)
SET(ARTOOLKIT_VIDEO_SOURCES_IPHONE
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/VideoiPhone/CameraVideo.m
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/VideoiPhone/cparams.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/VideoiPhone/MovieVideo.m
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/VideoiPhone/videoiPhone.m)
SET(ARTOOLKIT_VIDEO_SOURCES_MACOSX
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/VideoQuickTime/ARVideoSettingsController.m
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/VideoQuickTime/videoQuickTime.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/VideoQuickTime/videoQuickTimeMovie.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/VideoQuickTime7/QTKitVideo.m
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/VideoQuickTime7/videoQuickTime7.m)
SET(ARTOOLKIT_VIDEO_SOURCES_LINUX
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/VideoGStreamer/videoGStreamer.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/VideoLinux1394Cam/ver1/video1394V1.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/VideoLinux1394Cam/ver1/video1394V1format.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/VideoLinux1394Cam/ver1/video1394V1setting.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/VideoLinux1394Cam/ver2/video1394V2.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/VideoLinux1394Cam/ver2/video1394V2format.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/VideoLinux1394Cam/ver2/video1394V2setting.c
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/VideoLinuxV4L/videoV4L.c)
SET(ARTOOLKIT_VIDEO_SOURCES_WINDOWS
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/VideoWinDF/videoWinDF.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/VideoWinDS/videoWinDS.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/VideoWinDSVL/videoWinDSVL.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/VideoWinMC/CaptureFrameGrabber/CaptureFrameGrabber.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/VideoWinMC/CaptureFrameGrabber/MediaStreamSink.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/VideoWinMC/videoWinMC.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/VideoWinMC/WindowsMediaCapture.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/VideoWinMF/LogMediaType.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/SRC/VideoWinMF/videoWinMF.cpp)
